### ISSUE TITLE
pageSize设置稍大值时，快速滚动到底部会触发无限加载数据，即使数据已经足够渲染

### ISSUE THREAD

**Issue by catssay** [react-component/m-list-view#10]
感谢您将ListView组件移植到web平台。

遇到的问题：
----------------

在使用`ListView`组件的过程中发现当`pageSize`设置为稍大一点儿的值时，例如 10，快速滚动到页面底部会造成数据的不断加载，即使渲染的行数已经远远大于 `onEndReachedThreshold` 的值，仍然会不断触发`onEndReached` 请求数据；数据通过 `props` 接收；

问题分析：
-----------------

经对`ListVIew`组件研究后发现，测量底部是否进入可见视图的动作只在 `scroll` 事件中完成，当快速滚动到底部时, `getDistanceFromEnd(this.scrollProperties) < onEndReachedThreshold && curRenderedRowsCount === dataSource.getRowCount()` 成立，会触发一次 `onEndReached` ，fetch新的数据后`props`接收，依次调用 render -> _maybeCallOnEndReached -> _renderMoreRowsIfNeeded -> _pageInNewRows -> render -> _maybeCallOnEndReached ... `因为没有`scroll`事件，所以`getDistanceFromEnd(this.scrollProperties) < onEndReachedThreshold` 一直成立，从而陷入循环。

建议：
---------------
在` componentDidUpdate` 中对底部是否进入可见视图进行判断并设置 `scrollProperties`，例如：
```
componentDidUpdate() {
    const isVertical = !this.props.horizontal;
    const target = ReactDOM.findDOMNode(this.refs[SCROLLVIEW_REF]);

    this.scrollProperties.visibleLength = target[
      isVertical ? 'offsetHeight' : 'offsetWidth'
      ];
    this.scrollProperties.contentLength = target[
      isVertical ? 'scrollHeight' : 'scrollWidth'
      ];
    this.scrollProperties.offset = target[
      isVertical ? 'scrollTop' : 'scrollLeft'
      ];
  }
```

**Comment by warmhug** [comment]
麻烦先帮助确认这个问题：

- 是否也出现在 react-native 的原生 listview 中？
- 是否跟这个问题类似 https://github.com/ant-design/ant-design-mobile/issues/633#issuecomment-266508780
