### ISSUE TITLE
refactor for performance 

### ISSUE THREAD

**Issue by paranoidjk** [react-component/m-list-view#13]
add a new `List`  Component or refactor ?

-  https://github.com/seatgeek/react-infinite 
- https://facebook.github.io/react-native/blog/2017/03/13/better-list-views.html
- https://zhuanlan.zhihu.com/p/26022258

https://github.com/react-component/m-list-view/issues/1 https://github.com/react-component/m-list-view/issues/7

**Comment by paranoidjk** [comment]
https://github.com/react-component/m-list-view/issues/1

**Comment by paranoidjk** [comment]
https://github.com/react-component/m-list-view/issues/7

**Comment by benjycui** [comment]
ref: https://github.com/ant-design/ant-design/issues/3789

**Comment by paranoidjk** [comment]
close, no time to refactor this right now.
maintain a new [table-view](http://gitlab.alipay-inc.com/react-ui/tiny-table-view).
