### ISSUE TITLE
初始渲染结束后this.scrollProperties的值不对

### ISSUE THREAD

**Issue by McLemore** [react-component/m-list-view#17]
当我初始渲染了10条数据后，this.scrollProperties应该更新一次，this.scrollProperties.visibleLength和this.scrollProperties.contentLength不应该还是null

**Comment by warmhug** [comment]
可以调试下源码中 _renderMoreRowsIfNeeded 方法的调用时机，这个时机是不是符合你的需求？

**Comment by warmhug** [comment]
查看最新 demo 代码
