### ISSUE TITLE
refreshControl和useBodyScroll一起使用，this.scrollProperties.contentLength无法得到正确的值

### ISSUE THREAD

**Issue by McLemore** [react-component/m-list-view#18]
如果使用了refreshControl，div.am-list-view-scrollview会被设置style: position:absolute;导致div.am-list-view-scrollview的高度为0，所以this.scrollProperties.contentLength始终为0，得不到列表实际高度。

**Comment by warmhug** [comment]
确认你的内容不是空的？

**Comment by warmhug** [comment]
查看最新 demo 代码
