### ISSUE TITLE
大数据量的时候，ListView会动态的删除dom节点吗？

### ISSUE THREAD

**Issue by hufeng** [react-component/m-list-view#5]

**Comment by warmhug** [comment]
目前还不支持，这几周有计划加上

**Comment by hufeng** [comment]
hi @warmhug ，使用m-list-view包括antd-mobile的listview(基于m-list-view) 同样的代码，发现在android里面很顺畅，在ios滚动非常卡顿，但是访问线上demo却非常顺畅，比如下图，原封不动的代码，放在本地跑，在ios非常卡顿。
![image](https://cloud.githubusercontent.com/assets/533008/17992480/3fce77d4-6b7a-11e6-89d5-c1d6b19815a7.png)

**Comment by hufeng** [comment]
Sorry
