### ISSUE TITLE
调整

### ISSUE THREAD

**Issue by yiminghe** [react-component/m-list-view#7]
- refresh 不要附加到 ListView, 后期可能独立，使用 require('rmc-list-view/lib/RefreshControl');
- RefreshControl prefixCls 为 rmc-refresh-control

**Comment by warmhug** [comment]
ListView 里的 基础 list 布局和 scroll 事件处理 这些基础性代码是很少的，需要作为 RefreshControl /  zscroller / indexList /  pullup 功能的基础依赖。

体积和复杂度问题主要体现在 zscroller 、dataSource 数据处理，RefreshControl 依赖于 zscroller 里的实现比较鸡肋。

权衡很久不用改变，目前这个组件能覆盖 infinite 、模拟 scroller、pull up/down to refresh 等全部功能。
